import { StoreState } from './types';

// Initial data = the design mockup content, so a fresh install looks identical
// to Logit.dc.html. "Today" is pinned to 2026-06-30 (design reference date).
export const TODAY = '2026-06-30';

export const seed: StoreState = {
  records: [
    {
      id: 'r-running-0630',
      activity: '런닝',
      template: 'endurance',
      dateISO: '2026-06-30',
      timeLabel: '오후 6:30',
      meta: '한강공원 · 5.2km · 27′12″',
      rating: 4,
      companions: ['민지'],
      photos: [],
      memo: '노을이 좋았다. 마지막 1km 페이스 올림. 다음엔 7km 도전.',
      fields: { 거리: '5.2km', 시간: '27:12', 페이스: '5′14″', 고도: '42m', 평균심박: '152bpm', 칼로리: '328kcal' },
      sync: 'synced',
    },
    {
      id: 'r-musical-0629',
      activity: '뮤지컬',
      template: 'spectate',
      dateISO: '2026-06-29',
      timeLabel: '어제',
      meta: '〈레미제라블〉 · 블루스퀘어',
      rating: 5,
      companions: [],
      photos: [],
      memo: '3차 관람',
      fields: { 작품: '레미제라블', 공연장: '블루스퀘어', 회차: '3차' },
      sync: 'synced',
    },
    {
      id: 'r-cycling-0628',
      activity: '자전거',
      template: 'endurance',
      dateISO: '2026-06-28',
      timeLabel: '토요일',
      meta: '남산 순환 · 7.2km · 32′40″',
      rating: 4,
      companions: [],
      photos: [],
      memo: '오르막 구간 페이스 유지',
      fields: { 거리: '7.2km', 시간: '32:40', 페이스: '4′32″', 고도: '180m', 칼로리: '410kcal' },
      sync: 'synced',
    },
    {
      id: 'r-health-0626',
      activity: '헬스',
      template: 'setrep',
      dateISO: '2026-06-26',
      timeLabel: '목요일',
      meta: '가슴 · 총 볼륨 4,250kg',
      rating: 3,
      companions: [],
      photos: [],
      memo: '벤치프레스 신기록',
      fields: { 부위: '가슴', 총볼륨: '4,250kg', 운동시간: '52분' },
      sync: 'synced',
    },
    {
      id: 'r-running-0625',
      activity: '런닝',
      template: 'endurance',
      dateISO: '2026-06-25',
      timeLabel: '수요일',
      meta: '탄천 · 6.0km · 31′05″',
      rating: 4,
      companions: ['민지'],
      photos: [],
      memo: '가볍게 조깅',
      fields: { 거리: '6.0km', 시간: '31:05', 페이스: '5′11″', 고도: '12m', 칼로리: '360kcal' },
      sync: 'synced',
    },
  ],
  plans: [
    { id: 'p-health-0630', activity: '헬스', template: 'setrep', dateISO: '2026-06-30', timeLabel: '오후 8:00', place: '홈짐', reminder: true },
    { id: 'p-soccer-0702', activity: '축구', template: 'match', dateISO: '2026-07-02', timeLabel: '오후 3:00', place: '잠실 보조경기장', reminder: true },
    { id: 'p-concert-0703', activity: '콘서트', template: 'spectate', dateISO: '2026-07-03', timeLabel: '오후 7:30', place: '올림픽홀', memo: '아이유', reminder: true },
    { id: 'p-running-0705', activity: '런닝', template: 'endurance', dateISO: '2026-07-05', timeLabel: '오전 7:00', place: '한강공원', memo: '10km 목표', reminder: false },
  ],
  customActivities: [],
};
